/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'qyf' at '16-12-14 下午1:10' with Gradle 3.2.1
 *
 * @author qyf, @date 16-12-14 下午1:10
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public static void main(String[] args) {
        System.out.println("hello world");
    }
}
